version: '2'
services:
#  kafka:
#    build:
#      context: kafka
#      dockerfile: Dockerfile
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: $CF_HOST_IP
#      KAFKA_ZOOKEEPER_CONNECT: zk:2181
#      KAFKA_MESSAGE_MAX_BYTES: 2000000
#      KAFKA_CREATE_TOPICS: "Topic1:1:1"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock

  api:
    build: .
    ports:
      - "8080:8080"
#    depends_on:
#      - kafka